// apps/MishraShardendu22-Frontend-BlogWebsite/src/lib/components/Footer.svelte
<script lang="ts">
  import {
    Heart,
    Coffee,
    ArrowUpRight,
    Users,
    Rss,
    Folder,
    Award,
    Code,
    BookOpen,
    Shield,
    Package,
    Share2,
    Play,
    Camera,
    Terminal
  } from "lucide-svelte";

  const QUICK_LINKS = [
    { name: "Social Media", url: "https://mishrashardendu22.is-a.dev/links", icon: Users },
    { name: "RSS Feed", url: "https://mishrashardendu22.is-a.dev/feed.xml", icon: Rss },
    { name: "Project", url: "https://mishrashardendu22.is-a.dev/projects", icon: Folder },
    { name: "Certification", url: "https://mishrashardendu22.is-a.dev/certificates", icon: Award },
  ];

  const MY_WEBSITES = [
    { name: "Github Backup Lab", url: "https://github.mishrashardendu22.is-a.dev", icon: Code },
    { name: "Main", url: "https://mishrashardendu22.is-a.dev", icon: BookOpen },
    { name: "Admin Portal", url: "https://admin.mishrashardendu22.is-a.dev", icon: Shield },
    { name: "My UI Library", url: "https://pixel-art-8-bit.mishrashardendu22.is-a.dev", icon: Package },
  ];

  const SOCIAL_MEDIA = [
    { name: "Twitter", url: "https://x.com/Shardendu_M", icon: Share2 },
    { name: "LinkedIn", url: "https://www.linkedin.com/in/shardendumishra22", icon: Users },
    { name: "YouTube", url: "https://www.youtube.com/@Shardendu_Mishra", icon: Play },
    { name: "Instagram", url: "https://www.instagram.com/mishrashardendu22", icon: Camera },
  ];

  const CODING_PROFILES = [
    { name: "LeetCode", url: "https://leetcode.com/u/ShardenduMishra22/", icon: Award },
    { name: "GitHub Main", url: "https://github.com/MishraShardendu22", icon: Code },
    { name: "GitHub Learning", url: "https://github.com/ShardenduMishra22", icon: Folder },
    { name: "Codeforces", url: "https://codeforces.com/profile/MishraShardendu22", icon: Terminal },
  ];

  function handleScrollToTop() {
    window.scrollTo({
      top: 0,
      behavior: "smooth"
    });
  }
</script>

<footer class="w-full bg-[#09090b] border-t border-[#18181b] py-16 px-6 mt-16 relative overflow-hidden">
  <div class="max-w-7xl mx-auto relative z-10">
    <!-- Top section -->
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-12 mb-16">
      <div class="space-y-8">
        <div>
          <div class="flex items-center gap-3 mb-4">
            <span class="text-3xl font-bold text-white font-heading">Shardendu Mishra</span>
            <span class="text-xs px-2.5 py-0.5 rounded-full border border-[#7c3aed]/30 bg-[#7c3aed]/10 text-[#7c3aed] font-mono">
              Ecosystem
            </span>
          </div>
          <p class="text-[#a1a1aa] text-lg leading-relaxed max-w-xl">
            Software Engineer engineering modern, high-impact systems.
          </p>
        </div>

        <div class="flex items-center gap-2 text-sm text-zinc-500">
          <span>Made with</span>
          <Heart class="w-4 h-4 text-red-500" />
          <span>and</span>
          <Coffee class="w-4 h-4 text-[#7c3aed]" />
          <span>by Shardendu Mishra</span>
        </div>

        <div class="flex flex-wrap gap-3">
          <span class="px-4 py-2 bg-[#18181b] border border-[#27272a] rounded-lg text-xs text-zinc-300 font-semibold">
            Go
          </span>
          <span class="px-4 py-2 bg-[#7c3aed]/10 border border-[#7c3aed]/25 rounded-lg text-xs text-[#7c3aed] font-semibold">
            Svelte
          </span>
          <span class="px-4 py-2 bg-[#18181b] border border-[#27272a] rounded-lg text-xs text-zinc-300 font-semibold">
            Kubernetes
          </span>
          <span class="px-4 py-2 bg-[#18181b] border border-[#27272a] rounded-lg text-xs text-zinc-300 font-semibold">
            AI/ML
          </span>
        </div>

        <p class="text-xs text-zinc-650">
          &copy; 2026 Shardendu Mishra. All rights reserved.
        </p>
      </div>

      <!-- Right column contact prompt / quote -->
      <div class="flex flex-col justify-center space-y-6 lg:pl-12">
        <div class="border border-[#18181b] bg-[#09090b]/50 p-8 rounded-2xl">
          <h3 class="text-xl font-bold text-white mb-2 font-heading">Keep in Touch</h3>
          <p class="text-sm text-[#a1a1aa] mb-6">
            If you want to chat about engineering, technology, or have questions about my work, feel free to reach out.
          </p>
          <a
            href="https://mishrashardendu22.is-a.dev/#contact"
            class="inline-flex items-center gap-2 px-5 py-2.5 bg-[#7c3aed] hover:bg-[#8b5cf6] text-white text-sm font-semibold rounded-lg transition-colors duration-200"
          >
            <span>Send a Message</span>
            <ArrowUpRight class="w-4 h-4" />
          </a>
        </div>
      </div>
    </div>

    <!-- 4-Column Links Grid -->
    <div class="grid grid-cols-2 md:grid-cols-4 gap-12 pt-12 border-t border-[#18181b]">
      <!-- Quick Links -->
      <div>
        <h4 class="text-sm font-semibold text-zinc-200 mb-6 uppercase tracking-wider font-heading">Quick Links</h4>
        <ul class="space-y-4">
          {#each QUICK_LINKS as link}
            <li>
              <a
                href={link.url}
                class="flex items-center gap-2.5 text-sm text-[#a1a1aa] hover:text-[#7c3aed] transition-colors duration-200 group"
              >
                <svelte:component this={link.icon} class="w-4 h-4 text-zinc-500 group-hover:text-[#7c3aed] transition-colors" />
                <span>{link.name}</span>
              </a>
            </li>
          {/each}
        </ul>
      </div>

      <!-- My Websites -->
      <div>
        <h4 class="text-sm font-semibold text-zinc-200 mb-6 uppercase tracking-wider font-heading">My Websites</h4>
        <ul class="space-y-4">
          {#each MY_WEBSITES as link}
            <li>
              <a
                href={link.url}
                target="_blank"
                rel="noopener noreferrer"
                class="flex items-center gap-2.5 text-sm text-[#a1a1aa] hover:text-[#7c3aed] transition-colors duration-200 group"
              >
                <svelte:component this={link.icon} class="w-4 h-4 text-zinc-500 group-hover:text-[#7c3aed] transition-colors" />
                <span>{link.name}</span>
              </a>
            </li>
          {/each}
        </ul>
      </div>

      <!-- Social Media -->
      <div>
        <h4 class="text-sm font-semibold text-zinc-200 mb-6 uppercase tracking-wider font-heading">Social Media</h4>
        <ul class="space-y-4">
          {#each SOCIAL_MEDIA as link}
            <li>
              <a
                href={link.url}
                target="_blank"
                rel="noopener noreferrer"
                class="flex items-center gap-2.5 text-sm text-[#a1a1aa] hover:text-[#7c3aed] transition-colors duration-200 group"
              >
                <svelte:component this={link.icon} class="w-4 h-4 text-zinc-500 group-hover:text-[#7c3aed] transition-colors" />
                <span>{link.name}</span>
              </a>
            </li>
          {/each}
        </ul>
      </div>

      <!-- Coding Profiles -->
      <div>
        <h4 class="text-sm font-semibold text-zinc-200 mb-6 uppercase tracking-wider font-heading">Coding</h4>
        <ul class="space-y-4">
          {#each CODING_PROFILES as link}
            <li>
              <a
                href={link.url}
                target="_blank"
                rel="noopener noreferrer"
                class="flex items-center gap-2.5 text-sm text-[#a1a1aa] hover:text-[#7c3aed] transition-colors duration-200 group"
              >
                <svelte:component this={link.icon} class="w-4 h-4 text-zinc-500 group-hover:text-[#7c3aed] transition-colors" />
                <span>{link.name}</span>
              </a>
            </li>
          {/each}
        </ul>
      </div>
    </div>

    <!-- Banner & Scroll To Top -->
    <div class="mt-16 pt-8 border-t border-[#18181b] flex flex-col items-center gap-8">
      <div class="w-full flex justify-between items-center text-xs text-zinc-500">
        <span>&copy; 2026 Shardendu Mishra</span>
        <button
          type="button"
          on:click={handleScrollToTop}
          class="flex items-center gap-1.5 hover:text-[#7c3aed] transition-colors duration-200"
        >
          <span>Back to Top</span>
          <span>&uarr;</span>
        </button>
      </div>
    </div>
  </div>
</footer>

// frontend/src/components/main/footer.tsx
import Link from 'next/link'
import { Github, Linkedin, Mail, ArrowUp, Heart, Code, Coffee } from 'lucide-react'
import { Button } from '../ui/button'

export default function FooterSection() {
  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  const currentYear = new Date().getFullYear()

  return (
    <footer className="bg-gradient-to-br from-card via-card/95 to-secondary/10 border-t border-border/50 relative overflow-hidden">
      {/* Background decorative elements */}
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_80%,theme(colors.primary/2),transparent_70%)]"></div>
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,theme(colors.secondary/2),transparent_70%)]"></div>
      
      <div className="relative mx-auto max-w-7xl px-6 lg:px-8">
        {/* Main Footer Content */}
        <div className="py-16 grid grid-cols-1 lg:grid-cols-4 gap-12">
          {/* Brand Section */}
          <div className="lg:col-span-2 space-y-6">
            <div className="flex items-center space-x-3">
              <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-primary to-secondary flex items-center justify-center shadow-lg">
                <Code className="h-5 w-5 text-primary-foreground" />
              </div>
              <h3 className="text-2xl font-bold bg-gradient-to-r from-foreground to-primary bg-clip-text text-transparent">
                Shardendu Mishra
              </h3>
            </div>
            <p className="text-foreground/70 text-lg leading-relaxed max-w-md">
              Full-stack developer passionate about creating innovative solutions and building amazing user experiences.
            </p>
            <div className="flex items-center space-x-2 text-sm text-foreground/60">
              <span>Made with</span>
              <Heart className="h-4 w-4 text-red-500 fill-current" />
              <span>and</span>
              <Coffee className="h-4 w-4 text-amber-600" />
              <span>by Shardendu</span>
            </div>
          </div>

          <div className="space-y-6">
            <h4 className="text-lg font-semibold text-foreground">Quick Links</h4>
            <nav className="flex flex-col space-y-3">
              <Link href="/admin/dashboard" className="text-foreground/70 hover:text-primary transition-colors duration-300 hover:translate-x-1 transform">
                Admin
              </Link>
              <Link href="#about" className="text-foreground/70 hover:text-primary transition-colors duration-300 hover:translate-x-1 transform">
                About
              </Link>
              <Link href="#projects" className="text-foreground/70 hover:text-primary transition-colors duration-300 hover:translate-x-1 transform">
                Projects
              </Link>
              <Link href="#experience" className="text-foreground/70 hover:text-primary transition-colors duration-300 hover:translate-x-1 transform">
                Experience
              </Link>
              <Link href="#contact" className="text-foreground/70 hover:text-primary transition-colors duration-300 hover:translate-x-1 transform">
                Contact
              </Link>
            </nav>
          </div>

          {/* Connect Section */}
          <div className="space-y-6">
            <h4 className="text-lg font-semibold text-foreground">Connect</h4>
            <div className="flex flex-col space-y-4">
              <a
                href="https://github.com/shardendu-mishra"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center space-x-3 text-foreground/70 hover:text-primary transition-all duration-300 group"
              >
                <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center group-hover:bg-primary/20 transition-colors">
                  <Github className="h-4 w-4" />
                </div>
                <span>GitHub</span>
              </a>
              <a
                href="https://linkedin.com/in/shardendu-mishra"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center space-x-3 text-foreground/70 hover:text-primary transition-all duration-300 group"
              >
                <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center group-hover:bg-primary/20 transition-colors">
                  <Linkedin className="h-4 w-4" />
                </div>
                <span>LinkedIn</span>
              </a>
              <a
                href="mailto:shardendu@example.com"
                className="flex items-center space-x-3 text-foreground/70 hover:text-primary transition-all duration-300 group"
              >
                <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center group-hover:bg-primary/20 transition-colors">
                  <Mail className="h-4 w-4" />
                </div>
                <span>Email</span>
              </a>
            </div>
          </div>
        </div>

        {/* Bottom Section */}
        <div className="border-t border-border/30 py-8">
          <div className="flex flex-col md:flex-row justify-between items-center space-y-4 md:space-y-0">
            <div className="flex items-center space-x-6">
              <p className="text-sm text-foreground/60">
                © {currentYear} Shardendu Mishra. All rights reserved.
              </p>
              <div className="flex items-center space-x-4 text-xs text-foreground/50">
                <Link href="/privacy" className="hover:text-primary transition-colors">
                  Privacy
                </Link>
                <span>•</span>
                <Link href="/terms" className="hover:text-primary transition-colors">
                  Terms
                </Link>
              </div>
            </div>
            
            <Button
              onClick={scrollToTop}
              variant="outline"
              size="sm"
              className="group bg-background/50 backdrop-blur-sm border-primary/20 hover:border-primary/40 hover:bg-primary/5 transition-all duration-300"
            >
              <ArrowUp className="h-4 w-4 mr-2 transition-transform group-hover:-translate-y-1" />
              Back to Top
            </Button>
          </div>
        </div>
      </div>
    </footer>
  )
}
